# 公开访问
public: true

# 文件目录 默认程序启动目录下的uploads
Dir: 

# debug 模式
AppDebug: true

# 文件访问外链数组
ExternalLink:

# 项目运行端口
Port: ":23547"

# windows启动后自动打开浏览器
AutoOpenBrowser: false

# 同名文件覆盖上传
Overwrite: true


Logs:
  GinLogName: "/logs/gin.log"                  #设置 gin 框架的接口访问日志
  AppFileLogName: "/logs/low-file.log"    #设置项目运行时日志文件名，注意该名称不要与上一条重复 ,避免和 gin 框架的日志掺杂一起，造成混乱。
  TextFormat: "json"                                #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
  TimePrecision: "millisecond"                         #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 10                                           #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 7                                        #保留旧日志最大个数
  MaxAge: 15                                           #保留旧日志最大天数
  Compress: false